
version: '3.4'

services:
  consumer:
    image: consumer
    build:
      context: .
      dockerfile: Consumer/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
